FROM node:14.15.4

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

WORKDIR /app
 
# Copies package.json and package-lock.json to Docker environment
COPY package.json /app
COPY package-lock.json /app
 
# Installs all node packages
RUN npm install
 
# Copies everything over to Docker environment
COPY . /app
 
# Uses port which is used by the actual application
EXPOSE 3000
 
# Finally runs the application
CMD [ "npm", "start" ]